### ISSUE TITLE
add setting adminUrl rootUrl and baseUrl in clients

### ISSUE THREAD

**Issue by lutartur** [epam/edp-keycloak-operator#106]
Hello,
i try to configure  adminUrl/rootUrl/baseUrl for clients, but i have found nothing about that in documentation/crds definition.

please add the ability to configure adminUrl rootUrl and baseUrl in clients

**Comment by zmotso** [comment]
Hello @lutartur 

Currently, our operator only supports setting the `webUrl,` which is used for both `adminUrl` and `rootUrl`. Here’s an example:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
spec:
  webUrl: https://example.com
```  
At this time, `baseUrl` is not supported. I will add support for configuring `adminUrl`, `rootUrl`, and `baseUrl` to our backlog.

Thank you for your feedback!
