### ISSUE TITLE
Operator does not reconcile secret data

### ISSUE THREAD

**Issue by walnuss0815** [epam/edp-keycloak-operator#11]
**Describe the bug**
I am trying to set up a Kubernetes Cluster with Argo CD and Keycloak and I am using the Keycloak Operator to configure Keycloak. The Keycloak client is being deployed without `spec.secret` set and looks like the following:
```
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: argocd
  namespace: argocd
spec:
  advancedProtocolMappers: true
  clientId: argocd
  defaultClientScopes:
    - profile
    - email
  directAccess: true
  realmRef:
    kind: ClusterKeycloakRealm
    name: platform
  webUrl: <Removed>
```

To allow Argo CD to read the client secret from the generated k8s secret, the k8s secret must be annotated with `app.kubernetes.io/part-of: argocd` (see note here https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#2-configure-argo-cd-for-sso). To do so I am trying to use server side apply, which worked with the legacy Keycloak Operator from Red Hat:
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: 'ServerSideApply=true, Prune=false, Delete=false'
  labels:
    app.kubernetes.io/part-of: argocd
  name: keycloak-client-argocd-secret
  namespace: argocd
```

With the EDP Keycloak Operator this currently does not work, because the operator only checks if the k8s secret containing the client secret exists. But it does not verify that the actual client secret in the k8s secret exists (see https://github.com/epam/edp-keycloak-operator/blob/ecb5d430730f036de277b15f3262b0502fe77293/controllers/keycloakclient/chain/put_client.go#L131).

**To Reproduce**

1. Deploy Argo CD
2. Deploy Keycloak instance, EDP Operator and connect the Operator to Keycloak
3. Deploy a ClusterKeycloakRealm
4. Deploy the k8s secret above via Argo CD
5. Deploy the KeycloakClient above 

#### What did you expect to see?

I expect the operator to update the secret by adding the client secret key and value to the k8s secret.

#### What did you see instead? Under which circumstances?

The client secret was not added to the k8s secret.

**Kubernetes cluster type:**

vanilla

`$ kubectl version`

v1.27.1

**Comment by zmotso** [comment]
Hi @walnuss0815 
It is expected behavior from the operator's side.
Currently, we support two approaches:
1 If the KeycloakClient.spec.secret is empty - create a new Secret with the client password
2 If KeycloakClient.spec.secret is set, use the existing Secret with a predefined client password
As I understand, your approach is in the middle - you already have Secret, but the operator should set a password.
@SergK  Do we have a plan to add such functionality? We need a small change to add this.

**Comment by SergK** [comment]
@walnuss0815 I agree with @zmotso that this looks like a feature request. Honestly, I think we can put this on our roadmap.

Today we have a limited configuration of a secret which holds `client secret`. As @walnuss0815 mention,

If no secret is provided in KeycloakClient.spec.secret then operator will create a secret in the format:

```
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-<KEYCLOAKCLIENTNAME-secret
  data:
  clientSecret: SECRET
type: Opaque
```
if you want to provide your own secret, then `clientSecret` is a mandatory field we are looking for when creating client in keycloak realm

Meanwhile, here is how we configure argocd with keycloak-operator and ExternalSecret: https://github.com/epam/edp-install/tree/master/deploy-templates/templates/argocd
