### ISSUE TITLE
Add Keycloak Client Fine Grained Permissions

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#113]
**Is your feature request related to a problem? Please describe.**
I need a way to be able to enable the fine grained permissions on a client

**Describe the solution you'd like**
It would be good if we can enable this on the client the same way the UI seems to do it where it just creates a resource like this in the realm-management client Authorization permissions. 

```
- name: client.resource.EC31D644-C45A-4869-8F95-217FC33BF343
   type: Client
   ownerManagedAccess: false
   attributes: { }
   _id: cee46589-5ef4-4471-b8b9-ca6c09670c1d
   uris: [ ]
   scopes:
     - name: view
     - name: map-roles-client-scope
     - name: map-roles
     - name: configure
     - name: manage
     - name: map-roles-composite
     - name: token-exchange
```

**Describe alternatives you've considered**
No other alternatives

**Additional context**

![Screenshot 2024-12-12 at 9 06 39 PM](https://github.com/user-attachments/assets/edfd8d02-c4e3-49b8-a56c-4afec43be4f5)

I would like to be able to choose a policy for one of the permissions, in this case `token-exchange`.

![Screenshot 2024-12-12 at 9 10 27 PM](https://github.com/user-attachments/assets/024dd027-88ba-407f-8ccc-c15ee6232d7f)
