### ISSUE TITLE
Add support for Organization provisioning

### ISSUE THREAD

**Issue by srekkas** [epam/edp-keycloak-operator#115]
**Is your feature request related to a problem? Please describe.**
We cant provision Keycloak organisation automticaly

**Describe the solution you'd like**
this keycloak-operator provision Keycloak organisation

**Comment by jliokaitis** [comment]
yes it would be great to be able to manage keycloak organisations https://www.keycloak.org/docs/latest/release_notes/index.html#organizations-supported via operator

**Comment by zmotso** [comment]
Thank you for your suggestion. We’ve added this functionality to our backlog and aim to implement it in the near future. If you have specific requirements or use cases, feel free to share them with us.

**Comment by srekkas** [comment]
Found out that from Organization linked provider is configured same as Identity provider, so this part is already covered :)

`kind: KeycloakRealmIdentityProvider
  config:
    kc.org.broker.redirect.mode.email-matches: "true"
    kc.org.domain: example.com
`

**Comment by zmotso** [comment]
The Organization feature has been implemented and will be available in the upcoming release.
Configuration example:
```yaml
apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakOrganization
metadata:
  name: test-keycloak-organization
  namespace: default
spec:
  name: "Test Organization"
  alias: "test-org"
  domains:
    - "example.com"
    - "test.com"
  redirectUrl: "https://example.com/redirect"
  description: "Test organization"
  attributes:
    department:
      - "engineering"
      - "qa"
    location:
      - "us-east"
  identityProviders:
    - alias: "test-org-idp"
  realmRef:
    kind: KeycloakRealm
    name: test-org-realm

---

apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmIdentityProvider
metadata:
  name: test-org-idp
  namespace: default
spec:
  alias: "test-org-idp"
  enabled: true
  providerId: "github"
  realmRef:
    kind: KeycloakRealm
    name: test-org-realm
  config:
    clientId: "test-org-client-id"
    clientSecret: "test-org-client-secret"
    kc.org.domain: "example.com"
    kc.org.broker.redirect.mode.email-matches: "true"
```
