### ISSUE TITLE
KeycloakClient failing to reconcile when authorization field is empty

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#125]
**Describe the bug**

With `authorization: {}` getting added by the CRD, it seems to have issues if it does not have any authorization settings provided.

**To Reproduce**

#### What did you do?

Tried to create a client with admin fine grained permissions and nothing involving `authorization`, but the error is coming from the 
```
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: test
spec:
  adminFineGrainedPermissionsEnabled: true
  clientId: test
  defaultClientScopes:
  - auths
  - groups
  enabled: true
  fullScopeAllowed: true
  name: test
  permission:
    scopePermissions:
    - name: token-exchange
      policies:
      - token exchange policy
  realmRef:
    kind: KeycloakRealm
    name: test-realm
  redirectUris:
  - /*
  - http://localhost:8000
  secret: keycloak-client-test-secret
  serviceAccount:
    enabled: true
    realmRoles:
    - default-roles-test
  standardFlowEnabled: true
  webOrigins:
  - '*'
```

#### What did you expect to see?

A successful KeycloakClient reconcile 

#### What did you see instead? Under which circumstances?

```
unable to serve keycloak client: failed to serve handler: failed to get scopes: failed to get scopes: 404 Not Found: HTTP 404 Not Found: For more on this error consult the server log at the debug level.
```

**Kubernetes cluster type:**

vanilla

**Comment by dougkirkley** [comment]
Good news, it seems the automation I have for generating keycloak clients based on a config file was writing the `authorization: {}` to the keycloak yaml, so nothing wrong on the CRD side. I'm not sure if this should actually fail if it is provided and empty though. I'll leave that up to you guys to decide and if you have no issues with that we can close this.

**Comment by zmotso** [comment]
Closing this issue.
I haven't reproduced it on the latest version with the config:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
spec:
  authorization: {}
  adminUrl: https://admin.example.com
  advancedProtocolMappers: true
  attributes:
    post.logout.redirect.uris: +
  authorizationServicesEnabled: true
  clientAuthenticatorType: client-secret
  clientId: agocd
  directAccess: true
  enabled: true
  fullScopeAllowed: true
  homeUrl: /home/
  realmRef:
    kind: KeycloakRealm
    name: keycloakrealm-sample
  redirectUris:
    - /url1/*
    - /url2/*
  secret: $keycloak-client-keycloakclient-sample-secret:clientSecret
  serviceAccount:
    enabled: true
    realmRoles: null
  standardFlowEnabled: true
  webOrigins:
    - https://argocd.example.com
  webUrl: https://argocd.example.com
```
