### ISSUE TITLE
KeycloakRealmUser created requires the user to enter first name and last name on login

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#136]
Hello,

Is there a setting somewhere in the realm or the user resource that allows me to not requires users to have a first name and a last name?

Thanks

**Comment by zmotso** [comment]
Hi @dougkirkley.  For KeycloakRealmUser last/first name isn't required, you can skip them.
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: keycloakrealmuser-sample
spec:
  realmRef:
    name: keycloak-sample-test-bundle
    kind: KeycloakRealm
  username: "john.snow13"
  email: "john.snow13@example.com"
  enabled: true
```  
If you mean configuring the user profile - you can disable required user attributes by KeycloakRealm CR.
Example:
```yaml
  apiVersion: v1.edp.epam.com/v1
  kind: KeycloakRealm
  metadata:
    name: keycloakrealm-sample
    namespace: default
  spec:
    keycloakRef:
      kind: Keycloak
      name: keycloak-sample-test-bundle
    realmName: realm-sample
    userProfileConfig:
      attributes:
        - annotations:
            inputType: text
          displayName: ${lastName}
          group: test-group
          name: lastName
          permissions:
            edit:
              - admin
              - user
            view:
              - admin
              - user
      groups:
        - annotations:
            groupAnnotation: groupAnnotation
          displayDescription: Test Group
          displayHeader: Test Group
          name: test-group
      unmanagedAttributePolicy: ENABLED
```
If the attribute has `spec.userprofileConfig[].required{}`, it is required. If not - no.
Here we have another example of how to configure user profile:
https://github.com/epam/edp-keycloak-operator/blob/8561d0b554746dd38731a915e00bac1d2a80a532/deploy-templates/_crd_examples/keycloakrealm.yaml#L38C7-L72C30
