### ISSUE TITLE
Add the ability to specify pod and container security contexts

### ISSUE THREAD

**Issue by Interna1Error** [epam/edp-keycloak-operator#141]
**Is your feature request related to a problem? Please describe.**
Currently, the Operator deployment violates the restricted pod security standard as it does not set securityContext.seccompProfile.type and securityContext.capabilities. This prevents the Operator from being installed on a hardened cluster.

**Describe the solution you'd like**
The solution would be to make both pod and container security contexts configurable with respective helm chart values.

**Describe alternatives you've considered**
Setting the pod security standard to a less restrictive one is not an ideal solution as it might have potential security issues.

**Comment by daniil-nedostup** [comment]
Hi @Interna1Error!
I would like to inform you that PR #144 has been successfully merged, and the ability to configure security contexts will be available in the next release.

Example configuration in `values.yaml`:
```
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
```

Feel free to report any issues.
