### ISSUE TITLE
Keycloak Operator - remove deprecated fields from CRs

### ISSUE THREAD

**Issue by zmotso** [epam/edp-keycloak-operator#154]
We can remove deprecated fields from Keycloak Operator CRs.
Example:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: keycloakrealmuser-sample
spec:
  realm: keycloakrealm-sample   # deprecated, we can remove this property
  realmRef:                     # new way to set realm
    name: keycloakrealm-sample
    kind: KeycloakRealm
```
