### ISSUE TITLE
KeycloakClient service account users groups aren't being populated correctly

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#162]
When adding a group to a keycloak client service account, it isn't being reflected nor is it removing existing groups if they are there.

**To Reproduce**

#### What did you do?

```
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: test-client
spec:
  adminFineGrainedPermissionsEnabled: true
  clientId: test-client
  defaultClientScopes:
  - groups
  enabled: true
  fullScopeAllowed: true
  name: test-client
  realmRef:
    kind: KeycloakRealm
    name: test-realm
  redirectUris:
  - /*
  secret: keycloak-client-test-client-secret
  serviceAccount:
    enabled: true
    groups:
    - admin
    realmRoles:
    - default-roles-test-realm
  standardFlowEnabled: false
  webOrigins:
  - '*'
```

I tested locally adding prints around the operator and the group is properly picked up from the CR and the group is in the newGroups list before the keycloak api update user function call and no errors are returned

Would appreciate any help debugging this as it is my code :(

#### What did you expect to see?

The service account user is a member of the group `admin`

#### What did you see instead? Under which circumstances?

No groups exist for the service account user
