### ISSUE TITLE
Unable to create userProfileConfig without a group.

### ISSUE THREAD

**Issue by Tijs-2** [epam/edp-keycloak-operator#165]
**Describe the bug**
When I want add a userProfileConfig without attaching it to a group I receive an error.

**To Reproduce**

#### What did you do?

I tried to create the attribute like this:

```
    attributes:
      - name: "country"
        displayName: "Country"
        required:
          roles:
            - "user"
            - "admin"
        permissions:
          edit:
            - "user"
            - "admin"
          view:
            - "admin"
            - "user"
        annotations:
          inputType: "select"
        validations:
          options:
            options:
              sliceVal:
                - "Nederland"
                - "Belgie"
```

#### What did you see instead? Under which circumstances?

I get an error:
error during realm chain: chain failed SetLabels: chain failed PutUsers: chain failed PutUsersRoles: chain failed RealmSettings: chain failed AuthFlow: chain failed UserProfile: unable to update user profile: status: 400 Bad Request, body: {"errorMessage":"[Attribute 'country' references unknown group '']"} 

It seems it still adds the group to the request to keycloak, and if I am correct the group is optional so it should be left out?  https://www.keycloak.org/docs-api/latest/rest-api/index.html#UserProfileAttributeMetadata

`$ operator-sdk version`
I am using version 1.27.1
