### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Tijs-2** [epam/edp-keycloak-operator#167]
Is it possible to add translations when creating a KeycloakRealm. Not all the users can read English and I would like to add multiple languages.

**Describe the solution you'd like**
For me it would then be super nice that I can enable `Localization` and set the `Supported locales` and the `Default locale`.  In addition to that adding extra translations.

If I am correct they are added like this in the original export:
```
  "localizationTexts": {
    "en": {
      "profile.attributes.translation1": "English 1"
      "profile.attributes.translation2": "English 2"
    },
    "nl": {
      "profile.attributes.translation1": "Dutch 1"
      "profile.attributes.translation2": "Dutch 2"
    }
  },
```

So something like this would be nice:
```
localizationTexts:
  en:
      profile.attributes.translation1: "English 1"
      profile.attributes.translation2: "English 2"
  nl:
      profile.attributes.translation1: "Dutch 1"
      profile.attributes.translation2: "Dutch 2"
```
