### ISSUE TITLE
no guidance as for 'secret' format in keycloak CR

### ISSUE THREAD

**Issue by nnachefski** [epam/edp-keycloak-operator#2]
So i have a Keycloak instance:

```
apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak
  namespace: sso
spec:
  secret: keycloak-secret
  url: 'https://keycloak-sso.apps.okd.lab.arrowglance.io'
  adminType: user
```

But i cannot find any guidance as to what the 'secret' should look like.  Can you provide some?

Thanks!
-Nick

**Comment by m-yosefpor** [comment]
Thank you epam for providing this operator to the community.

From code I found this:

in user mode:

```
apiVersion: v1
kind: Secret
metadata:
  name:  keycloak-creds
type: Opaque
stringData:
  username: "someuser"
  password: "somepass"
```

in client-secret mode:

```
apiVersion: v1
kind: Secret
metadata:
  name:  keycloak-creds
type: Opaque
stringData:
  clientSecret: "someclientsecret"
```

I have tested the user mode and it's connecting to keycloak. However it requires some objects to name as `main` to work. eg. `Keycloak` or `KeycloakRealm`. Also some other features such as `KeycloakRealmUser` requires a already created real via `KeycloakRealm` so you can not use externally provisioned realms. Moreover, other objects such as `KeycloakClient` requries a `secret` which is also a k8s secret, which you need to find in code on how to use it. There are many errors you might encounter during testing which can be found from operator logs, there are no `event`ing on the objects.
