### ISSUE TITLE
Enable secret support in KeycloakRealmIdentityProvider resource

### ISSUE THREAD

**Issue by zmotso** [epam/edp-keycloak-operator#20]
Currently, we set clientSecret as plain text.
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmIdentityProvider
metadata:
  name: keycloakrealmidentityprovider-sample
spec:
  realmRef:
    kind: KeycloakRealm
    name: realm
  alias: instagram
  authenticateByDefault: false
  enabled: true
  firstBrokerLoginFlowAlias: "first broker login"
  providerId: "instagram"
  config:
    clientId: "foo"
    clientSecret: "some-secret"
    hideOnLoginPage: "true"
    syncMode: "IMPORT"
    useJwksUrl: "true"
```
We need to have the possibility to set clientSecret from the Kubernetes secret.

**Comment by zmotso** [comment]
Added secret reference in format: `$secretName:secretKey`.
Example:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmIdentityProvider
metadata:
  name: keycloakrealmidentityprovider-sample
spec:
  realmRef:
    kind: KeycloakRealm
    name: realm
  alias: instagram
  firstBrokerLoginFlowAlias: "first broker login"
  providerId: "instagram"
  config:
    clientId: "foo"
    clientSecret: "$secretName:secretKey"
```
