### ISSUE TITLE
Enable secret support in KeycloakClient resource

### ISSUE THREAD

**Issue by SergK** [epam/edp-keycloak-operator#21]
We need to be able to use secret from Kubernetes Secret object instead of definition in spec for KeycloakClient:

```
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
spec:
  realmRef:
    name: keycloakrealm-sample
    kind: KeycloakRealm
  advancedProtocolMappers: true
  clientId: agocd
  directAccess: true
  public: false
  secret: ''
  webUrl: https://argocd.example.com
  defaultClientScopes:
    - groups
  redirectUris:
    - /url1/*
    - /url2/*
```
Related issue: https://github.com/epam/edp-keycloak-operator/issues/20

**Comment by zmotso** [comment]
Example:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
spec:
  realmRef:
    name: keycloakrealm-sample
    kind: KeycloakRealm
  advancedProtocolMappers: true
  clientId: agocd
  directAccess: true
  public: false
  secret: $client-secret-name:client-secret-key
  webUrl: https://argocd.example.com
  defaultClientScopes:
    - groups
  redirectUris:
    - /url1/*
    - /url2/*
 ```
