### ISSUE TITLE
Enable secret support in KeycloakRealmComponent resource

### ISSUE THREAD

**Issue by regiontog** [epam/edp-keycloak-operator#30]
**Is your feature request related to a problem? Please describe.**
Unable to manage LDAP bind credentials in kubernetes secrets.

```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmComponent
metadata:
  name: ldap
spec:
  realm: testrealm
  name: ldap
  providerId: ldap
  providerType: org.keycloak.storage.UserStorageProvider
  config:
    bindCredential:
      - passwordMustBeInCleartextHere
    bindDn:
      - uid=serviceaccount,cn=users,dc=example,dc=com
    connectionUrl:
      - ldaps://dc.intranet.com
    vendor:
      - ad
    ...
```

**Describe the solution you'd like**
Being able to reference kubernetes secret values in KeycloakRealmComponent config. Like in #21 and #20 

**Describe alternatives you've considered**
Having a separate secretConfig property under spec.
