### ISSUE TITLE
Keycloak URL CA

### ISSUE THREAD

**Issue by srekkas** [epam/edp-keycloak-operator#36]
**Is your feature request related to a problem? Please describe.**
 I want to connect to Keycloak cluster service, which is HTTPS, how to trust service CA certificate?
Because i got error, certificate is trusted by unknown authority.

**Describe the solution you'd like**
Add way to add CA parameter, e.g. from secret.

**Describe alternatives you've considered**
Connect over HTTP service or Ingress.

**Additional context**

**Comment by dougkirkley** [comment]
Would be nice if this took in the same schema as https://pkg.go.dev/k8s.io/api/core/v1#EnvFromSource. So it can accept either a`ConfigMapRef` or `SecretRef` in case people are using configMaps with a CA trust bundle.

**Comment by zmotso** [comment]
@srekkas  We have added this functionality to the master branch, 
and it will be included in an upcoming release.
Now operator supports two options for Keycloak/ClusterKeycloak:
- `caCert` for certificates
- `insecureSkipVerify` to skip certificate verification

@dougkirkley Thank you for the advice.

Examples of how to use:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-with-ca-cert-secret
spec:
  secret: keycloak-secret
  url: https://test-keycloak:8443
  caCert:
    secretKeyRef:
      name: test-keycloak-certs
      key: ca.crt

---

apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-with-ca-cert-configmap
spec:
  secret: keycloak-secret
  url: https://test-keycloak:8443
  caCert:
    configMapKeyRef:
      name: test-keycloak-certs
      key: ca.crt

---

apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-with-insecure-flag
spec:
  secret: keycloak-secret
  url: https://test-keycloak:8443
  insecureSkipVerify: true

``` 

Related tests with certificates setup:
https://github.com/epam/edp-keycloak-operator/blob/master/tests/e2e/keycloak-selfsigned-certificates/01-install-keycloak-server.yaml#L60
https://github.com/epam/edp-keycloak-operator/blob/master/tests/e2e/keycloak-selfsigned-certificates/02-install-keycloak-resource.yaml
