### ISSUE TITLE
Operator not working on okd 4.14 because of rbac issues

### ISSUE THREAD

**Issue by Elyytscha** [epam/edp-keycloak-operator#37]
i wasn't able to install the operator successfully on openshift, the operator was crashlooping because of permission errors for clusterkeycloaks and clusterkeycloakrealms api's

i added the following crb's to fix it

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edp-keycloak-operator-controller-manager-clusterkeycloakrealms
subjects:
  - kind: ServiceAccount
    name: edp-keycloak-operator-controller-manager
    namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterkeycloakrealms.v1.edp.epam.com-v1alpha1-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edp-keycloak-operator-controller-manager-clusterkeycloaks
subjects:
  - kind: ServiceAccount
    name: edp-keycloak-operator-controller-manager
    namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterkeycloaks.v1.edp.epam.com-v1alpha1-admin
```

**Comment by NikolayMarusenko** [comment]
Hello @Elyytscha !

Could you kindly provide some clarification on the process for installing the operator? Are you utilizing [Operatorhub](https://operatorhub.io/operator/edp-keycloak-operator) for this purpose? We will check this case.

Thank you for contribution!

**Comment by Elyytscha** [comment]
i thought because i wrote openshift it would be clear that its handled by olm via subscription :)

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: edp-keycloak-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: edp-keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: edp-keycloak-operator.v1.19.0
```

i'm sorry for not communicating it correctly initially
