### ISSUE TITLE
Ability to Configure Realm Token Settings

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#38]
**Is your feature request related to a problem? Please describe.**
The KeycloakRealm resource is missing the ability to configure token settings e.g. accessTokenLifespan

**Describe the solution you'd like**
Add the accessToken* and refreshToken* fields to the KeycloakRealm resource

**Describe alternatives you've considered**
The only alternative is the keycloak-operator from Keycloak that allows this configuration on one import only, or manually via the console.

**Comment by zmotso** [comment]
Hi, @dougkirkley, We are investigating this feature.
It isn't hard to implement, and we will do it soon.

**Comment by zmotso** [comment]
@dougkirkley We have added support for `tokenSettings`.
This will be included in the nearest release.

Example:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: keycloakrealm-sample
spec:
  tokenSettings:
    accessTokenLifespan: 300
    accessCodeLifespan: 300
    accessToken: 300
    actionTokenGeneratedByAdminLifespan: 300
    actionTokenGeneratedByUserLifespan: 300
    refreshTokenMaxReuse: 300
    revokeRefreshToken: true
    defaultSignatureAlgorithm: RS256
```
