### ISSUE TITLE
Deprecate SSORealm functional

### ISSUE THREAD

**Issue by zmotso** [epam/edp-keycloak-operator#47]
We have filed the `KeycloakRealm`  CR (sso..) to set up the parent realm and identity provider. 
A big part of this configuration is hardcoded, not configurable, and has bugs.
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: keycloakrealm-sample
spec:
  realmName: realm-sample
  keycloakRef:
    name: keycloak-sample
    kind: Keycloak
  ssoRealmName: master
  ssoRealmEnabled: false
  ssoAutoRedirectEnabled: false
```
This functionality can be created by separate CRs - `KeycloakRealm` + `KeycloakRealmIdentityProvider` and the approach is more flexible. 
Remove deprecated sso configuration from the KeycloakRealm CR.
