### ISSUE TITLE
Allow configuring a realm/keycloak in a different namespace

### ISSUE THREAD

**Issue by BronzeDeer** [epam/edp-keycloak-operator#5]
**Is your feature request related to a problem? Please describe.**
At work we are currently building out an internal developer platform that will use Keycloak as IdP for all in-cluster applications. Due to security and coupling concerns we will need to separate out the applications from different stream teams into separate namespaces, while the keycloak realm will be configured in a platform-team-owned namespace. Each application should be able to get an OIDC client with individual clientId and clientSecret  by deploying a KeycloakClient CR in its own namespace. 

Currently the Operator does not support this, since it only searches the namespace of the custom resource for a matching realm resource https://github.com/epam/edp-keycloak-operator/blob/8c3936aaa065140bc537dfc8c4bae5067bd57cf7/controllers/helper/controller_helper.go#L245
https://github.com/epam/edp-keycloak-operator/blob/8c3936aaa065140bc537dfc8c4bae5067bd57cf7/controllers/keycloakclient/client_realm_owner.go#L47
https://github.com/epam/edp-keycloak-operator/blob/8c3936aaa065140bc537dfc8c4bae5067bd57cf7/controllers/keycloakclient/client_realm_owner.go#L59

**Describe the solution you'd like**
The best solution would be to add an optional extra Field to the CRs (e.g. `targetRealmNamespace`/`keycloakOwnerNamespace`) which if present will make the operator search for a Realm/Keycloak in that namespace rather than in the same namespace as the CR. Without the field present, the behaviour would stay the exact same as now, conferring perfect forward compatibility.

If api stability dictates that the CRs cannot be extended with optional Fields at all, then allowing `targetRealm`/`keycloakOwner` to be specified not just by name but optionally in the form of `<namespace>/<name>` or `<namespace>:<name>` to cause the same behaviour change would allow for this usecase as well

**Describe alternatives you've considered**
Our current prototype uses the Keycloak Realm Operator (i.e. the fork of the old official Operator) which can find Realms/Keycloak Instances in any namespace by label, if its service account has sufficient permissions. Unfortunately the realm operator can only add/delete realms and is therefore incompatible with a GitOps Workflow using the Operator Pattern.

Added the edp-keycloak-operator-managed realm into the realm operator as external realm is an option, however at that point we would be using 3 different operators (Quarkus, Realm, and EDP) per cluster to deploy and manage a single Keycloak deployment each which is clearly undesirable from both operations and security perspectives.

**Additional context**
If we can decide which of the two proposed solutions should be implemented, I'd be happy to contribute a PR to that effect

**Comment by SergK** [comment]
Hello @BronzeDeer ,

Thank you for bringing up such a significant topic. We have some relevant use-cases from our end. I will do my best to provide a helpful answer. Here is how we envision implementing it within the Operator scope.

Our proposal is to create new Cluster Wide Resources: **ClusterKeycloak** and **ClusterKeycloakRealm**. This approach aligns with how it is implemented in other operators like cert-manager, tekton, and external-secret-operator. By doing this, we can present Keycloak and KeycloakRealm "as a service" and reference them from our Custom Resources. Please refer to the diagram below for a visual representation.

<img width="911" alt="image" src="https://github.com/epam/edp-keycloak-operator/assets/1520525/708c7e69-b44e-45a3-8fee-521ebfeb3f61">

With such approach we can gradually deprecate **targetRealm** from KeycloakClient and replace it with RealmRef:
```
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name:  myclient
spec:
  advancedProtocolMappers: true
  clientId: harbor
  defaultClientScopes:
    - profile
    - email
    - roles
  directAccess: true
  protocolMappers:
    - config:
        access.token.claim: 'true'
        claim.name: roles
        id.token.claim: 'true'
        multivalued: 'true'
        userinfo.token.claim: 'true'
      name: roles
      protocol: openid-connect
      protocolMapper: oidc-usermodel-realm-role-mapper
  secret: keycloak-client-harbor-secret
  webUrl: https://harbor.exampl.com
  targetRealm: myrealm   <===DEPRECATION
  realmRef:                        <=== NEW
    - kind: ClusterKeycloakRealm
      name: myrealm
```

the same is true for KeycloakRealm:

```
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: test
spec:
  keycloakOwner: main    <=== DEPRECATION
  realmName: my-ns-realm
  ssoRealmEnabled: true
  ssoRealmName: openshift
  keycloakRef:                  <=== NEW
    - kind: ClusterKeycloak
      name: my-keycloak
```
or for Cluster scope resource
```
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloakRealm
metadata:
  name: clusterscope
spec:
  realmName: my-ns-realm
  ssoRealmEnabled: true
  ssoRealmName: openshift
  keycloakRef:
    - kind: ClusterKeycloak
      name: my-keycloak
```

This approach requires the implementation of two new CR and Controllers for them

@BronzeDeer does it work in your case?

Thanks,
Sergiy
