### ISSUE TITLE
Add Resources to Authorization struct for KeycloakClients

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#75]
**Is your feature request related to a problem? Please describe.**
Adding the Resources to the Authorization filed for KeycloakClient will make it so you can add scopes to certain Resources, e.g: Allowing clients via the realm-management client to do token-exchange.

**Describe the solution you'd like**
Add the Resources list to the Authorization struct for KeycloakClient

**Describe alternatives you've considered**
No alternative

**Additional context**
<img width="1424" alt="Screenshot 2024-07-17 at 9 49 49 AM" src="https://github.com/user-attachments/assets/ee73ec9c-3fe1-4afd-97f2-78b61c1b0da0">

**Comment by zmotso** [comment]
Hi @dougkirkley 
Thank you for your suggestion. We will consider this change and begin working on it.

**Comment by zmotso** [comment]
We implemented this functionality.
Example:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-authorization-sample
spec:
  realmRef:
    name: keycloakrealm-sample
    kind: KeycloakRealm
  clientId: authorization-sample
  webUrl: https:///example.com
  directAccess: true
  authorizationServicesEnabled: true
  serviceAccount:
    enabled: true
  authorization:
    scopes:
      - scope-example
    resources:
      - name: resource-example
        displayName: Resource example
        type: test
        iconUri: https://example.com/icon.png
        scopes:
          - scope-example
```
