### ISSUE TITLE
As a user of keycloak operator I want to be able to configure SubComponent of component in a realm

### ISSUE THREAD

**Issue by thorgull** [epam/edp-keycloak-operator#8]
**Is your feature request related to a problem? Please describe.**
In keycloak the components of type org.keycloak.storage.UserStorageProvider can have sub components of type org.keycloak.storage.ldap.mappers.LDAPStorageMapper

From the keyclaok admin API point of view those subComponent are just almost like any other component, with the exception that the property parentId is not the id of the realm but the id of the component they belong to.

With the current KeycloakRealmComponents resource I am not able to create those LDAPStorageMapper sub component

**Describe the solution you'd like**
In the keycloak API, the ComponentRepresentation contains a "parentId" field. This field is already present in the adapter but never used.
The problem could maybe be solved by defining a parent property in the KeycloakRealmComponents CRD that reference another KeycloakRealmComponent.
Then when trying to create or update a component with a parent specified, we can lookup up for the ID and pass it in the parentId field.

I imagine something like that as configuration.
```apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmComponent
metadata:
  name: ad-user-provider
spec:
  name: Active Directory
  providerId: ldap
  providerType: org.keycloak.storage.UserStorageProvider
  realm: onemrva-agents
  config:
    ...
---
`apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmComponent
metadata:
  name: ad-role-mapper
spec:
  name: Role Mapper
  providerId: role-ldap-mapper
  providerType: org.keycloak.storage.ldap.mappers.LDAPStorageMapper
  realm: onemrva-agents
  parent: ad-user-provider
  config:
    ...
```

**Describe alternatives you've considered**
I don't see alternative at current time.
I apologize if I missed another way to achieve this. I look in the source code and don't find any way to do that type of configuration...

**Comment by thorgull** [comment]
Can I propose this kind of solution :

https://github.com/epam/edp-keycloak-operator/compare/master...thorgull:edp-keycloak-operator:master

**Comment by zmotso** [comment]
Hi @thorgull,
Thanks for the suggestion. We plan to consider its implementation shortly.

**Comment by zmotso** [comment]
Hi @thorgull,
The feature is in the master branch.
Docker image: epamedp/keycloak-operator:1.17.0-SNAPSHOT.15
Example:
```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmComponent
metadata:
  name: component-sample
spec:
  realm: keycloakrealm-sample
  name: component-sample
  providerId: scope
  providerType: "org.keycloak.services.clientregistration.policy.ClientRegistrationPolicy"

---

apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmComponent
metadata:
  name: component-sample-child
spec:
  realm: keycloakrealm-sample
  name: component-sample-child
  providerId: scope
  providerType: "org.keycloak.services.clientregistration.policy.ClientRegistrationPolicy"
  parentRef:
    name: component-sample
    kind: KeycloakRealmComponent
```
